sudo: required

#use only specify which branches to build
#or use except to make the blacklist
branches:
  only: 
     - dev

#specify recipients that will be notified about build results
#default send to the committer and the author
#notifications:
#  email:
#    recipients:
#      - v-limhua@microsoft.com

language: cpp

#use docker
services:
  - docker

#build docker
install:
  - docker build -t multiverso .

#run with the test.sh
script:
  - docker run -t -i multiverso /etc/bootstrap.sh
