sudo: required
branches:
  only:
    - liming
notifications:
  email:
    recipients:
      - v-limhua@microsoft.com
language: cpp
services:
  - docker
install:
  - docker build -t multiverso .
script:
  - docker run -t -i multiverso /etc/bootstrap.sh
#  - docker run -t -i multiverso /bin/bash -c "/etc/bootstrap.sh /bin/bash; mpiexec -n 2 build/bin/multiverso.test checkpoint"
#  - docker run -t -i multiverso /bin/bash -c "/etc/bootstrap.sh /bin/bash; mpiexec -n 2 build/bin/multiverso.test ttt"
#  - mpiexec -n 2 build/bin/multiverso.test matrix
#  - mpiexec -n 2 build/bin/multiverso.test array
#  - mpiexec -n 2 build/bin/multiverso.test checkpoint
#  - mpiexec -n 2 build/bin/multiverso.test restore
#  - mpiexec -n 2 build/bin/multiverso.test kv
