sudo: required
branches:
  only:
    - liming
notifications:
  email:
    recipients:
      - v-limhua@microsoft.com
language: cpp
services:
  - docker
before_install:
  - docker build -t multiverso .
  - docker run -t -i multiverso /bin/bash -c "cd /project"
  - docker ps -a
install: true
#  - docker run -t -i multiverso /bin/bash -c "mpiexec -n 2 /project/build/bin/multiverso.test matrix" 
script:
  - mpiexec -n 2 build/bin/multiverso.test matrix
  - mpiexec -n 2 build/bin/multiverso.test array
  - mpiexec -n 2 build/bin/multiverso.test checkpoint
  - mpiexec -n 2 build/bin/multiverso.test restore
  - mpiexec -n 2 build/bin/multiverso.test kv
